name: "publish github package"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
      - name: publish
        run: npm publish
        working-directory: my-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
