name: "publish github package"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
      - run: cat /home/runner/work/_temp/.npmrc
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: npm publish --registry=https://npm.pkg.github.com/
        working-directory: my-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
