name: Node.js Package

on: workflow_dispatch

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4
    - uses: action/setup-node@v3
      with:
        registry-url: https://npm.pkg.github.com
        scope: '@javeedambu'
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
